<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Vendor;

class VendorSeeder extends Seeder{
    public function run(): void{

    $vendors=[
     [
                'name'        => 'The Flower Shop',
                'category'    => 'decoration',
                'phoneNumber' => '03795481',
                'description' => 'Professional flower decoration for all events.',
                'locations'   => ['Hadi Nasrallah Avenue, Al Afak Institute Bldg., Haret Hreik, Beirut'],
                'instagram'   => 'theflowershoplb',
                'rating'      => 4.8,
                'imageIcon'   => 'images/theflowershop.jpeg',
            ],
            [
                'name'        => 'Cremino',
                'category'    => 'catering',
                'phoneNumber' => '01 453 800',
                'description' => 'High-end dessert shop offering specialty & custom cakes, ice cream & chocolates.',
                'locations'   => [
                    'Roma Street, Centre Miraj Building, Sanayeh, Beirut',
                    'Old Airport Road, Beirut',
                    'Hadath, Baabda, Lebanon',
                    'Saida–Tyre Highway, near Abbasiyeh exit, Tyre',
                ],
                'instagram'   => 'cremino.lb',
                'rating'      => 4.6,
                'imageIcon'   => 'images/cremino.jpeg',
            ],
            [
                'name'        => 'Aljawad Dining',
                'category'    => 'catering',
                'phoneNumber' => '03 456 854',
                'description' => 'Outdoor seating. Great cocktails. Vegan options.',
                'locations'   => [
                    'New Airport Road, beside Golf Club, Beirut',
                    'Centro Mall, Jnah, Beirut',
                    'Ghobeiry, Baabda, Lebanon',
                    'Michel Zakhour Street, Chyah, Baabda',
                    'Saida–Tyre Highway, Abbasiyeh, Tyre',
                ],
                'instagram'   => 'aljawaddining',
                'rating'      => 4.3,
                'imageIcon'   => 'images/jawad.jpeg',
            ],
            [
                'name'        => 'Planto',
                'category'    => 'decoration',
                'phoneNumber' => '03 921 490',
                'description' => 'A modern flower shop in Beirut known for artistic and elegant floral arrangements.',
                'locations'   => ['Hadi Nasrallah Highway, Beirut'],
                'instagram'   => 'plantoleb',
                'rating'      => 2.5,
                'imageIcon'   => 'images/planto.jpeg',
            ],
            [
                'name'        => 'Lancaster Eden Bay',
                'category'    => 'venue',
                'phoneNumber' => '01 838 000',
                'description' => "Beirut's most luxurious ballroom venue, accommodating up to 600 guests for fairytale events.",
                'locations'   => ['El Akhtal El Saghir Street, Ramlet El Baida, Beirut'],
                'instagram'   => 'lancasteredenbay',
                'rating'      => 3.3,
                'imageIcon'   => 'images/lancaster.jpeg',
            ],

            [
    'name'        => 'Le Royal Hotel Beirut',
    'category'    => 'venue',
    'phoneNumber' => '04 555 000',
    'description' => 'Luxury hotel offering elegant wedding halls, outdoor terraces, and event spaces.',
    'locations'   => ['Dbayeh, Mount Lebanon'],
    'instagram'   => 'leroyalbeirut',
    'rating'      => 4.7,
    'imageIcon'   => 'images/leroyal.jpeg',
],
[
    'name'        => 'Kempinski Summerland Hotel & Resort',
    'category'    => 'venue',
    'phoneNumber' => '01 858 000',
    'description' => 'Luxury seaside resort with indoor and outdoor venues for weddings and celebrations.',
    'locations'   => ['Jnah, Beirut'],
    'instagram'   => 'summerlandlb',
    'rating'      => 4.8,
    'imageIcon'   => 'images/summerland.jpeg',
],
[
    'name'        => 'BIEL',
    'category'    => 'venue',
    'phoneNumber' => '01 962 000',
    'description' => 'One of Lebanon\'s largest exhibition and event venues for weddings and corporate events.',
    'locations'   => ['Downtown Beirut'],
    'instagram'   => 'bielbeirut',
    'rating'      => 4.5,
    'imageIcon'   => 'images/biel.jpeg',
],
[
    'name'        => 'Patchi',
    'category'    => 'catering',
    'phoneNumber' => '01 482 222',
    'description' => 'Luxury chocolates and premium event favors for weddings and celebrations.',
    'locations'   => ['Hazmieh, Baabda'],
    'instagram'   => 'patchi',
    'rating'      => 4.8,
    'imageIcon'   => 'images/patchi.jpeg',
],
[
    'name'        => 'Le Chef Catering',
    'category'    => 'catering',
    'phoneNumber' => '01 447 447',
    'description' => 'Professional Lebanese and international catering services for private and corporate events.',
    'locations'   => ['Beirut'],
    'instagram'   => 'lechefcateringlb',
    'rating'      => 4.4,
    'imageIcon'   => 'images/lechef.jpeg',
],
[
    'name'        => 'Hallab 1881',
    'category'    => 'catering',
    'phoneNumber' => '06 444 555',
    'description' => 'Traditional Lebanese sweets, desserts, and catering for weddings and celebrations.',
    'locations'   => [
        'Tripoli',
        'Verdun, Beirut',
    ],
    'instagram'   => 'hallab1881',
    'rating'      => 4.7,
    'imageIcon'   => 'images/hallab.jpeg',
],
[
    'name'        => 'Pulse Production',
    'category'    => 'photography',
    'phoneNumber' => '03 777 240',
    'description' => 'Wedding photography and cinematic videography services across Lebanon.',
    'locations'   => ['Beirut'],
    'instagram'   => 'pulseproductionlb',
    'rating'      => 4.9,
    'imageIcon'   => 'images/pulse.jpeg',
],
[
    'name'        => 'Pixel Studio',
    'category'    => 'photography',
    'phoneNumber' => '03 800 550',
    'description' => 'Professional wedding photography, engagement sessions, and event coverage.',
    'locations'   => ['Jounieh'],
    'instagram'   => 'pixelstudiolb',
    'rating'      => 4.7,
    'imageIcon'   => 'images/pixel.jpeg',
],
[
    'name'        => 'Moments Photography',
    'category'    => 'photography',
    'phoneNumber' => '03 944 882',
    'description' => 'Creative wedding and event photography with cinematic storytelling.',
    'locations'   => ['Beirut'],
    'instagram'   => 'momentsphotographylb',
    'rating'      => 4.6,
    'imageIcon'   => 'images/moments.jpeg',
],
[
    'name'        => 'Mix FM DJs',
    'category'    => 'music',
    'phoneNumber' => '01 999 666',
    'description' => 'Professional DJs, sound systems, and lighting for weddings and private events.',
    'locations'   => ['Beirut'],
    'instagram'   => 'mixfmlb',
    'rating'      => 4.7,
    'imageIcon'   => 'images/mixfm.jpeg',
],
[
    'name'        => 'The Band Lebanon',
    'category'    => 'music',
    'phoneNumber' => '03 556 774',
    'description' => 'Live entertainment band performing Arabic and international music for weddings.',
    'locations'   => ['Beirut'],
    'instagram'   => 'thebandlebanon',
    'rating'      => 4.8,
    'imageIcon'   => 'images/theband.jpeg',
],
[
    'name'        => 'DJ Rodge',
    'category'    => 'music',
    'phoneNumber' => '03 333 666',
    'description' => 'Popular Lebanese wedding DJ and event entertainer.',
    'locations'   => ['Beirut'],
    'instagram'   => 'djrodge',
    'rating'      => 4.9,
    'imageIcon'   => 'images/djrodge.jpeg',
],
[
    'name'        => 'Exotica',
    'category'    => 'decoration',
    'phoneNumber' => '01 611 611',
    'description' => 'Luxury floral arrangements and event decoration for weddings and special occasions.',
    'locations'   => [
        'Achrafieh, Beirut',
        'Jal El Dib',
    ],
    'instagram'   => 'exoticalb',
    'rating'      => 4.8,
    'imageIcon'   => 'images/exotica.jpeg',
],
[
    'name'        => 'Fleurs de Joie',
    'category'    => 'decoration',
    'phoneNumber' => '01 200 300',
    'description' => 'Elegant floral design and customized wedding decoration.',
    'locations'   => ['Achrafieh, Beirut'],
    'instagram'   => 'fleursdejoie',
    'rating'      => 4.7,
    'imageIcon'   => 'images/fleurs.jpeg',
],
[
    'name'        => 'Maison des Fleurs',
    'category'    => 'decoration',
    'phoneNumber' => '01 612 345',
    'description' => 'Premium floral arrangements and event styling for weddings and luxury celebrations.',
    'locations'   => ['Beirut'],
    'instagram'   => 'maisondesfleurslb',
    'rating'      => 4.6,
    'imageIcon'   => 'images/maison.jpeg',
],

            [
                'name'        => 'Al Anwar Nasheed Group',
                'category'    => 'music',
                'phoneNumber' => '+961 3 123 456',
                'description' => 'Professional nasheed group specializing in mawled performances, Islamic praises, and spiritual entertainment for weddings, celebrations, and religious events.',
                'locations'   => ['Beirut, Lebanon', 'Tripoli, Lebanon', 'Sidon, Lebanon'],
                'instagram'   => 'alanwarnasheed',
                'rating'      => 4.9,
                'imageIcon'   => 'images/alanwar.jpeg',
            ],
            [
                'name'        => 'Mawled Masters Ensemble',
                'category'    => 'music',
                'phoneNumber' => '+961 71 234 567',
                'description' => 'Traditional mawled performers offering authentic Islamic chanting, munshid vocals, and daff percussion. Perfect for religious gatherings, mawled nights, and family events.',
                'locations'   => ['Beirut, Lebanon', 'Baalbek, Lebanon', 'Nabatieh, Lebanon'],
                'instagram'   => 'mawledmasters',
                'rating'      => 4.7,
                'imageIcon'   => 'images/mawledmasters.jpeg',
            ],
            [
                'name'        => 'Nour Al Qoloub',
                'category'    => 'music',
                'phoneNumber' => '+961 76 345 678',
                'description' => '"Light of Hearts" – A renowned nasheed group providing soulful Islamic music, mawlid recitations, and halal entertainment with a cappella performances and daff rhythms.',
                'locations'   => ['Beirut, Lebanon', 'Jounieh, Lebanon', 'Byblos, Lebanon'],
                'instagram'   => 'nouralqoloub',
                'rating'      => 4.8,
                'imageIcon'   => 'images/nouralqoloub.jpeg',
            ],
            [
                'name'        => 'Samaa Islamic Choir',
                'category'    => 'music',
                'phoneNumber' => '+961 70 456 789',
                'description' => 'Halal vocal ensemble performing nasheeds, mawled anthems, and spiritual songs. All-female group available for women-only events. Instrument-free, pure a cappella.',
                'locations'   => ['Beirut, Lebanon', 'Zahle, Lebanon', 'Tyre, Lebanon'],
                'instagram'   => 'samaa.choir',
                'rating'      => 4.5,
                'imageIcon'   => 'images/samaa.jpeg',
            ],
            [
                'name'        => 'Rihlat Al Anwar',
                'category'    => 'music',
                'phoneNumber' => '+961 81 567 890',
                'description' => '"Journey of Lights" – Interactive storytelling and mawled performance group. Combines engaging Seerah narratives with traditional nasheed segments for an immersive educational experience.',
                'locations'   => ['Beirut, Lebanon', 'Saida, Lebanon', 'Sour, Lebanon'],
                'instagram'   => 'rihlatalanwar',
                'rating'      => 4.6,
                'imageIcon'   => 'images/rihlat.jpeg',
            ],
            [
                'name'        => 'Al Bayraq Nasheed',
                'category'    => 'music',
                'phoneNumber' => '+961 03 678 901',
                'description' => 'Lebanon-based nasheed group with over 10 years of experience. Specializes in mawled celebrations, Islamic weddings, and community events. Daff and vocal harmony.',
                'locations'   => ['Beirut, Lebanon', 'Tripoli, Lebanon', 'Akkar, Lebanon'],
                'instagram'   => 'albayraqnasheed',
                'rating'      => 4.4,
                'imageIcon'   => 'images/albayraq.jpeg',
            ],
            [
                'name'        => 'Zikr Ensemble Beirut',
                'category'    => 'music',
                'phoneNumber' => '+961 71 789 012',
                'description' => 'Traditional zikr and mawled performers. Authentic Islamic chanting with daff and vocal harmonies. Available for mawled nights, religious conferences, and spiritual gatherings.',
                'locations'   => ['Beirut, Lebanon', 'Chouf, Lebanon', 'Metn, Lebanon'],
                'instagram'   => 'zikrensemble',
                'rating'      => 4.7,
                'imageIcon'   => 'images/zikr.jpeg',
            ],
            [
                'name'        => 'Nashid Al Fajr',
                'category'    => 'music',
                'phoneNumber' => '+961 76 890 123',
                'description' => '"Dawn Nasheed" – Professional vocal group offering halal music for all events. Specializes in mawled celebrations, religious holidays, and family-friendly entertainment.',
                'locations'   => ['Beirut, Lebanon', 'Jbeil, Lebanon', 'Batroun, Lebanon'],
                'instagram'   => 'nashidalfajr',
                'rating'      => 4.3,
                'imageIcon'   => 'images/nashidalfajr.jpeg',
            ],
            [
                'name'        => 'Al Rawda Entertainment',
                'category'    => 'music',
                'phoneNumber' => '+961 03 901 234',
                'description' => 'Full-service halal entertainment provider. Offers nasheed performances, mawled recitations, storytelling for kids, and event hosting. Complete package for mawled events.',
                'locations'   => ['Beirut, Lebanon', 'Baabda, Lebanon', 'Jounieh, Lebanon'],
                'instagram'   => 'alrawdaent',
                'rating'      => 4.5,
                'imageIcon'   => 'images/alrawda.jpeg',
            ],
            [
                'name'        => 'Bassel & The Munshideen',
                'category'    => 'music',
                'phoneNumber' => '+961 70 012 345',
                'description' => 'Led by renowned munshid Bassel, this group delivers powerful mawled performances with traditional Arabic maqamat. Perfect for grand celebrations and spiritual events.',
                'locations'   => ['Beirut, Lebanon', 'Sidon, Lebanon', 'Tripoli, Lebanon'],
                'instagram'   => 'basselmunshid',
                'rating'      => 4.9,
                'imageIcon'   => 'images/bassel.jpeg',
            ],
            // ========== HALAL MUSIC VENDORS (MAWLED / NASHEED) ==========
            [
                'name'        => 'Al Anwar Nasheed Group',
                'category'    => 'music',
                'phoneNumber' => '+961 3 123 456',
                'description' => 'Professional nasheed group specializing in mawled performances, Islamic praises, and spiritual music for weddings, celebrations, and religious events.',
                'locations'   => ['Beirut, Lebanon', 'Tripoli, Lebanon', 'Sidon, Lebanon'],
                'instagram'   => 'alanwarnasheed',
                'rating'      => 4.9,
                'imageIcon'   => 'images/alanwar.jpeg',
            ],
            [
                'name'        => 'Mawled Masters Ensemble',
                'category'    => 'music',
                'phoneNumber' => '+961 71 234 567',
                'description' => 'Traditional mawled performers offering authentic Islamic chanting, munshid vocals, and daff percussion. Perfect for religious gatherings, mawled nights, and family events.',
                'locations'   => ['Beirut, Lebanon', 'Baalbek, Lebanon', 'Nabatieh, Lebanon'],
                'instagram'   => 'mawledmasters',
                'rating'      => 4.7,
                'imageIcon'   => 'images/mawledmasters.jpeg',
            ],
            [
                'name'        => 'Nour Al Qoloub',
                'category'    => 'music',
                'phoneNumber' => '+961 76 345 678',
                'description' => '"Light of Hearts" – A renowned nasheed group providing soulful Islamic music, mawlid recitations, and halal entertainment with a cappella performances and daff rhythms.',
                'locations'   => ['Beirut, Lebanon', 'Jounieh, Lebanon', 'Byblos, Lebanon'],
                'instagram'   => 'nouralqoloub',
                'rating'      => 4.8,
                'imageIcon'   => 'images/nouralqoloub.jpeg',
            ],
            [
                'name'        => 'Samaa Islamic Choir',
                'category'    => 'music',
                'phoneNumber' => '+961 70 456 789',
                'description' => 'Halal vocal ensemble performing nasheeds, mawled anthems, and spiritual songs. All-female group available for women-only events. Instrument-free, pure a cappella.',
                'locations'   => ['Beirut, Lebanon', 'Zahle, Lebanon', 'Tyre, Lebanon'],
                'instagram'   => 'samaa.choir',
                'rating'      => 4.5,
                'imageIcon'   => 'images/samaa.jpeg',
            ],
            [
                'name'        => 'Rihlat Al Anwar',
                'category'    => 'music',
                'phoneNumber' => '+961 81 567 890',
                'description' => '"Journey of Lights" – Interactive storytelling and mawled performance group. Combines engaging Seerah narratives with traditional nasheed segments for an immersive educational experience.',
                'locations'   => ['Beirut, Lebanon', 'Saida, Lebanon', 'Sour, Lebanon'],
                'instagram'   => 'rihlatalanwar',
                'rating'      => 4.6,
                'imageIcon'   => 'images/rihlat.jpeg',
            ],
            [
                'name'        => 'Al Bayraq Nasheed',
                'category'    => 'music',
                'phoneNumber' => '+961 03 678 901',
                'description' => 'Lebanon-based nasheed group with over 10 years of experience. Specializes in mawled celebrations, Islamic weddings, and community events. Daff and vocal harmony.',
                'locations'   => ['Beirut, Lebanon', 'Tripoli, Lebanon', 'Akkar, Lebanon'],
                'instagram'   => 'albayraqnasheed',
                'rating'      => 4.4,
                'imageIcon'   => 'images/albayraq.jpeg',
            ],
            [
                'name'        => 'Zikr Ensemble Beirut',
                'category'    => 'music',
                'phoneNumber' => '+961 71 789 012',
                'description' => 'Traditional zikr and mawled performers. Authentic Islamic chanting with daff and vocal harmonies. Available for mawled nights, religious conferences, and spiritual gatherings.',
                'locations'   => ['Beirut, Lebanon', 'Chouf, Lebanon', 'Metn, Lebanon'],
                'instagram'   => 'zikrensemble',
                'rating'      => 4.7,
                'imageIcon'   => 'images/zikr.jpeg',
            ],
            [
                'name'        => 'Nashid Al Fajr',
                'category'    => 'music',
                'phoneNumber' => '+961 76 890 123',
                'description' => '"Dawn Nasheed" – Professional vocal group offering halal music for all events. Specializes in mawled celebrations, religious holidays, and family-friendly entertainment.',
                'locations'   => ['Beirut, Lebanon', 'Jbeil, Lebanon', 'Batroun, Lebanon'],
                'instagram'   => 'nashidalfajr',
                'rating'      => 4.3,
                'imageIcon'   => 'images/nashidalfajr.jpeg',
            ],
            [
                'name'        => 'Al Rawda Entertainment',
                'category'    => 'music',
                'phoneNumber' => '+961 03 901 234',
                'description' => 'Full-service halal entertainment provider. Offers nasheed performances, mawled recitations, storytelling for kids, and event hosting. Complete package for mawled events.',
                'locations'   => ['Beirut, Lebanon', 'Baabda, Lebanon', 'Jounieh, Lebanon'],
                'instagram'   => 'alrawdaent',
                'rating'      => 4.5,
                'imageIcon'   => 'images/alrawda.jpeg',
            ],
            [
                'name'        => 'Bassel & The Munshideen',
                'category'    => 'music',
                'phoneNumber' => '+961 70 012 345',
                'description' => 'Led by renowned munshid Bassel, this group delivers powerful mawled performances with traditional Arabic maqamat. Perfect for grand celebrations and spiritual events.',
                'locations'   => ['Beirut, Lebanon', 'Sidon, Lebanon', 'Tripoli, Lebanon'],
                'instagram'   => 'basselmunshid',
                'rating'      => 4.9,
                'imageIcon'   => 'images/bassel.jpeg',
            ],
[
    'name'        => 'Lebanese Philharmonic Orchestra',
    'category'    => 'music',
    'phoneNumber' => '+961 1 123 456',
    'description' => 'Lebanon\'s premier orchestra performing classical masterpieces. Available for gala events, weddings, and cultural celebrations with a full symphony or chamber ensemble. Repertoire includes Beethoven, Mozart, Bach, and traditional Lebanese works.',
    'locations'   => ['Beirut, Lebanon'],
    'instagram'   => 'lebanesephilharmonic',
    'rating'      => 4.9,
    'imageIcon'   => 'images/lphilharmonic.jpeg',
],
[
    'name'        => 'Antonine University Choir',
    'category'    => 'music',
    'phoneNumber' => '+961 71 540 419',
    'description' => 'One of Lebanon\'s leading choral ensembles since 1978. Performs major works of the choral tradition including Mozart\'s "Requiem," Handel\'s "Messiah," and Haydn\'s "Nelson Mass." Available for concerts, religious events, and festivals. Has performed at Carnegie Hall and Baalbeck International Festival.[citation:8]',
    'locations'   => ['Beirut, Lebanon', 'Baalbeck, Lebanon'],
    'instagram'   => 'uachoir',
    'rating'      => 4.8,
    'imageIcon'   => 'images/uachoir.jpeg',
],
[
    'name'        => 'USJ Choir',
    'category'    => 'music',
    'phoneNumber' => '+961 71 540 419',
    'description' => 'Saint Joseph University Choir founded in 2015, featuring over 70 singers. Covers Baroque to Contemporary music with notable performances of Mozart\'s "Requiem," Bach\'s "St. John Passion," and Handel\'s "Messiah." Collaborates with the Lebanese Philharmonic Orchestra.[citation:15]',
    'locations'   => ['Beirut, Lebanon'],
    'instagram'   => 'usjchoir',
    'rating'      => 4.7,
    'imageIcon'   => 'images/usjchoir.jpeg',
],
[
    'name'        => 'Trio Khalife',
    'category'    => 'music',
    'phoneNumber' => '+961 1 234 567',
    'description' => 'Renowned Lebanese classical ensemble featuring Marcel Khalife (oud), Rami Khalife (piano), and Sary Khalife (cello). Blends classical Western traditions with Eastern influences. Headlined at Al Bustan International Festival. Perfect for high-end events and cultural gatherings.[citation:11]',
    'locations'   => ['Beirut, Lebanon', 'Beit Mery, Lebanon'],
    'instagram'   => 'triokhalife',
    'rating'      => 4.9,
    'imageIcon'   => 'images/triokhalife.jpeg',
],
[
    'name'        => 'Wadih Sabra Ensemble',
    'category'    => 'music',
    'phoneNumber' => '+961 3 456 789',
    'description' => 'Ensemble dedicated to performing the works of Wadih Sabra, composer of the Lebanese national anthem and pioneer of classical music in Lebanon. Repertoire includes his Arabic operas, classical compositions, and works from the early 20th century Lebanese tradition.[citation:2][citation:6]',
    'locations'   => ['Beirut, Lebanon'],
    'instagram'   => 'wadihsabraensemble',
    'rating'      => 4.6,
    'imageIcon'   => 'images/wadihsabra.jpeg',
],
[
    'name'        => 'Fadia Tomb El-Hage',
    'category'    => 'music',
    'phoneNumber' => '+961 1 345 678',
    'description' => 'Lebanese contralto and one of the few singers mastering both Western and Middle Eastern classical traditions. Former Rahbani brothers singer and Fairouz collaborator. Available for solo recitals and ensemble performances of Medieval to Contemporary works.[citation:13]',
    'locations'   => ['Beirut, Lebanon'],
    'instagram'   => 'fadiatombelhage',
    'rating'      => 4.8,
    'imageIcon'   => 'images/fadiaelhage.jpeg',
],
[
    'name'        => 'Jeunesses Musicales du Liban Orchestra',
    'category'    => 'music',
    'phoneNumber' => '+961 1 456 789',
    'description' => 'Youth orchestra bringing classical music to audiences across Lebanon. Collaborates with leading choirs including USJ Choir. Performs masterpieces from Baroque to Contemporary. Available for concerts, festivals, and special events.[citation:15]',
    'locations'   => ['Beirut, Lebanon', 'Jounieh, Lebanon'],
    'instagram'   => 'jmliban',
    'rating'      => 4.5,
    'imageIcon'   => 'images/jmlorchestra.jpeg',
],
[
    'name'        => 'Mozart Chahine School of Music Ensemble',
    'category'    => 'music',
    'phoneNumber' => '+961 1 361 992',
    'description' => 'Classical ensemble from one of Lebanon\'s oldest musical institutions (founded 1948). Features professional musicians and advanced students performing classical repertoire. Available for corporate events, weddings, and private functions.[citation:1]',
    'locations'   => ['Beirut, Lebanon', 'Jal El Dib, Lebanon'],
    'instagram'   => 'mozartchahine',
    'rating'      => 4.4,
    'imageIcon'   => 'images/mozartchahine.jpeg',
],
[
    'name'        => 'Riwaya Ensemble',
    'category'    => 'music',
    'phoneNumber' => '+961 76 123 456',
    'description' => 'Classical ensemble featuring music by Middle Eastern composers including Lebanese works. Performs pieces by Sami Seif, Bushra El-Turk, and others. Blends classical training with Arabic maqam traditions. Available for cultural events and concerts.[citation:4]',
    'locations'   => ['Beirut, Lebanon'],
    'instagram'   => 'riwayaensemble',
    'rating'      => 4.5,
    'imageIcon'   => 'images/riwaya.jpeg',
],
[
    'name'        => 'Nidaa Abou Mrad & Classical Arabic Music Ensemble',
    'category'    => 'music',
    'phoneNumber' => '+961 1 567 890',
    'description' => 'Classical Arabic music ensemble of Antonine University. Specializes in music from Lebanon and the Levant of the Arab Renaissance period. Repertoire includes works by Mīhāīl Maššāqa (1800-1888) and traditional Bashraf compositions.[citation:10]',
    'locations'   => ['Beirut, Lebanon'],
    'instagram'   => 'nidaaaboumrad',
    'rating'      => 4.6,
    'imageIcon'   => 'images/nidaaensemble.jpeg',
],


    ];
    foreach($vendors as $data){
        Vendor::updateOrCreate(['name'=>$data['name']],$data);
    }
    }
    }
