<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('reports', function (Blueprint $table) {
            // Primary Key
            $table->id();
            
            // ✅ REQUIRED: Foreign Key to events (one report per event)
            $table->foreignId('event_id')
                  ->unique()
                  ->constrained('events')
                  ->onDelete('cascade');
            // Explanation: Which event this report is for
            // Why unique? Each event has ONE summary report
            // If event deleted, report deleted too
            // Report generated after event completion
            
            // ✅ REQUIRED: Summary Text
            $table->text('summary');
            // Example: "Wedding event for 150 guests. Total budget: 75,000 SAR.
            //          Successfully managed with 98% budget utilization.
            //          All vendors paid on time. 145 guests attended."
            // Why required? Every report needs a summary
            // Generated by: Application logic analyzing event data
            
            // ✅ DERIVED: Guest Count
            $table->integer('guest_count_derived');
            // Explanation: Total number of guests who attended (checked in)
            // Calculated from: COUNT guests WHERE check_in_time IS NOT NULL
            // Why derived? Could calculate on-demand, but storing improves performance
            // Example: 145 (out of 150 invited)
            
            // ✅ DERIVED: Budget Utilization Percentage
            $table->decimal('budget_utilization_derived', 5, 2);
            // Explanation: Percentage of budget spent
            // Calculated from: (total_spent / budget_overall) * 100
            // Why DECIMAL(5,2)? Range 0.00 to 999.99 (allows over 100%)
            // Example: 98.67 means 98.67% of budget used
            
            // ✅ DERIVED: Vendor Status Summary (JSON)
            $table->json('vendor_status_json');
            // Explanation: Summary of all vendor bookings and payments
            // Why JSON? Flexible structure for multiple vendors
            
            // Example structure:
            // {
            //   "total_vendors": 5,
            //   "booked": 5,
            //   "paid": 4,
            //   "pending_payment": 1,
            //   "vendors": [
            //     {"name": "Royal Catering", "status": "booked", "payment": "paid"},
            //     {"name": "Grand Ballroom", "status": "booked", "payment": "pending"}
            //   ]
            // }
            
            // ✅ DERIVED: Task Completion Rate
            $table->decimal('task_completion_rate_derived', 5, 2);
            // Explanation: Percentage of tasks completed
            // Calculated from: (completed_tasks / total_tasks) * 100
            // Why DECIMAL(5,2)? Range 0.00 to 100.00
            // Example: 95.00 means 95% of tasks completed
            
            $table->timestamps(); // created_at, updated_at
            // created_at = when report was first generated
            // updated_at = when report was last regenerated/updated
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('reports');
    }
};
